---
services:
  one-time-links-api:
    build: .
    ports:
      - "80:8080"
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health/"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
